[PREP]
data_dir = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/5SppBalanced/Wave"
output_dir = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/5SpeciesBalanced/"
audio_format = "wav"
annot_format = "koumura"
labelset = "1"
train_dur = 10
val_dur = 10
test_dur = 10
annot_file = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/5SppBalanced/Annotation.xml"

[SPECT_PARAMS]
fft_size = 512
step_size = 32
freq_cutoffs = [ 500, 10000,]
thresh = 6.25
transform_type = "log_spect"

[DATALOADER]
window_size = 88

[TRAIN_CHECKPOINT]
checkpoint_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/5SpeciesBalanced/5SppBalanced_Patience18_Model_results_220107_112909/max-val-acc-checkpoint.pt"
labelmap_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/5SpeciesBalanced/5SppBalanced_Patience18_Model_results_220107_112909/labelmap.json"
spect_scaler_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/5SpeciesBalanced/5SppBalanced_Patience18_Model_results_220107_112909/StandardizeSpect"
models = [ "TweetyNet",]
batch_size = 3
num_epochs = 10
normalize_spectrograms = true
val_step = 50
ckpt_step = 200
patience = 50
root_results_dir = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/5SpeciesBalanced/"
csv_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/5SpeciesBalanced/5SpeciesBalanced_MASTER.csv"

[TweetyNet.optimizer]
lr = 0.001
