[PREP]
annot_file = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/Zonotrichia_leucophrys/Annotation.xml"
annot_format = "koumura"
audio_format = "wav"
data_dir = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/Zonotrichia_leucophrys/Wave"
labelset = "1"
output_dir = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Zonotrichia_leucophrys/"
test_dur = 10
train_dur = 10
val_dur = 10

[SPECT_PARAMS]
fft_size = 512
freq_cutoffs = [ 500, 10000,]
step_size = 32
thresh = 6.25
transform_type = "log_spect"

[DATALOADER]
window_size = 88

[TRAIN_CHECKPOINT]
batch_size = 3
checkpoint_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Zonotrichia_leucophrys/ZL_Patience50-16-38_Model_results_211116_111859/max-val-acc-checkpoint.pt"
ckpt_step = 200
csv_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Zonotrichia_leucophrys/ZL_Wave_prep_211110_173704_MASTER.csv"
labelmap_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Zonotrichia_leucophrys/ZL_Patience50-16-38_Model_results_211116_111859/labelmap.json"
models = [ "TweetyNet",]
normalize_spectrograms = true
num_epochs = 10
patience = 50
root_results_dir = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Zonotrichia_leucophrys/"
spect_scaler_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Zonotrichia_leucophrys/ZL_Patience50-16-38_Model_results_211116_111859/StandardizeSpect"
val_step = 50


[TweetyNet.optimizer]
lr = 0.001
