[PREP]
audio_format = "wav"
data_dir = "/Users/kprovost/Documents/TweetyNet/testing_wcs/Zonotrichia_leucophrys_train/Wave"
output_dir = "/Users/kprovost/Documents/TweetyNet/testing_wcs/Zonotrichia_leucophrys_train"

[SPECT_PARAMS]
fft_size = 512
freq_cutoffs = [ 500, 10000,]
step_size = 64
thresh = 6.25
transform_type = "log_spect"

[PREDICT]
batch_size = 11
checkpoint_path = "/Users/kprovost/Documents/TweetyNet/FINISHED_MODELS_BY_SPECIES/Zonotrichia_leucophrys/210602_142402_Zonotrichia_leucophrys_notransfer/max-val-acc-checkpoint.pt"
labelmap_path = "/Users/kprovost/Documents/TweetyNet/FINISHED_MODELS_BY_SPECIES/Zonotrichia_leucophrys/210602_142402_Zonotrichia_leucophrys_notransfer/labelmap.json"
majority_vote = false
models = "TweetyNet"
num_workers = 4
output_dir = "/Users/kprovost/Documents/TweetyNet/testing_wcs/Zonotrichia_leucophrys_train/Predictions"
spect_scaler_path = "/Users/kprovost/Documents/TweetyNet/FINISHED_MODELS_BY_SPECIES/Zonotrichia_leucophrys/210602_142402_Zonotrichia_leucophrys_notransfer/StandardizeSpect"

[TweetyNet.optimizer]
lr = 0.001
