[PREP]
data_dir = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/Myiarchus.tuberculifer/Wave"
output_dir = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/Myiarchus.tuberculifer/"
audio_format = "wav"
annot_format = "birdsong-recognition-dataset"
labelset = "1"
train_dur = 10
val_dur = 10
test_dur = 10
annot_file = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/Myiarchus.tuberculifer/Annotation.xml"

[SPECT_PARAMS]
fft_size = 512
step_size = 32
freq_cutoffs = [ 500, 15000,]
thresh = 6.25
transform_type = "log_spect"

[DATALOADER]
window_size = 88

[EVAL]
batch_size = 10
csv_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Poecile.carolinensis/PC_Wave_prep_220803_165018_MASTER.csv"
output_dir = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Poecile.carolinensis/"
device = "cpu"
models = [ "TweetyNet",]
checkpoint_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Melozone.fusca/results_220908_161443/TweetyNet/checkpoints/max-val-acc-checkpoint.pt"
labelmap_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Melozone.fusca/results_220908_161443/labelmap.json"
spect_scaler_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Melozone.fusca/results_220908_161443/StandardizeSpect"

[TweetyNet.optimizer]
lr = 0.001
