## set the folder that has the annotations in it 
folder = "~/Documents/Research/Chondestes_grammacus/"
pattern = ".wav.csv"

## get all the files in the folder that are annotations
my_files = list.files(path=folder,
                      pattern=".wav.csv$",
                      full.names = TRUE,
                      recursive = TRUE)

## loop over each file with an lapply

my_annots = sapply(my_files,FUN=function(x){
  df = read.table(x,header=T,sep=",")
  labels = df$label
  ulab = unique(labels)
  ## return that sum duration to the list generated by lapply
  return(ulab)
})
unique(my_annots)

my_durations = lapply(my_files,FUN=function(x){
  
  ## read the file "x" into R as a dataframe
  df = read.table(x,header=T,sep=",")

  ## extract the duration in seconds of all the data in that file
  duration = df[,2] - df[,1]

  ## sum the duration
  sum_duration = sum(duration,na.rm=TRUE) ## na.rm removes blanks before summing

  ## return that sum duration to the list generated by lapply
  return(sum_duration)

})

## give the durations names for easy access
names(my_durations) = basename(my_files) ## basename removes the folder part of a file name

## turn my_durations into a data.frame

my_df = do.call(rbind,my_durations)

## split the names up
my_names = lapply(rownames(my_df),FUN=function(x){
  y=strsplit(x,"-")[[1]][1:3]
})

## turn the names into a data.frame
names_df = do.call(rbind,my_names)

## combine the two data.frames
combo_df = cbind(my_df,names_df)

## need to add column names
colnames(combo_df) = c("duration","genus","species","XC")

## convert combo_df to the right format
combo_df = as.data.frame(combo_df)
combo_df$duration = as.numeric(combo_df$duration)

## sum up the durations by species
#table(combo_df[,c("duration","species")]) ## oops wrong function
agg_df = aggregate(combo_df$duration~combo_df$species,FUN = sum)
sum(agg_df[,2])
