[PREP]
data_dir = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/Zonotrichia.leucophrys/Wave"
output_dir = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/Zonotrichia.leucophrys/"
audio_format = "wav"
annot_format = "birdsong-recognition-dataset"
labelset = "1"
train_dur = 10
val_dur = 10
test_dur = 10
annot_file = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/Zonotrichia.leucophrys/Annotation.xml"

[SPECT_PARAMS]
fft_size = 512
step_size = 32
freq_cutoffs = [ 500, 15000,]
thresh = 6.25
transform_type = "log_spect"

[DATALOADER]
window_size = 88

[EVAL]
batch_size = 10
output_dir = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Zonotrichia.leucophrys/"
csv_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Zonotrichia.leucophrys/ZL_Wave_prep_211110_173704_MASTER.csv"
device = "cpu"
models = [ "TweetyNet",]
checkpoint_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Myiarchus.tuberculifer/results_220803_144442/TweetyNet/checkpoints/max-val-acc-checkpoint.pt"
labelmap_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Myiarchus.tuberculifer/results_220803_144442/labelmap.json"
spect_scaler_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Myiarchus.tuberculifer/results_220803_144442/StandardizeSpect"

[TweetyNet.optimizer]
lr = 0.001
