[PREP]
data_dir = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/Calypte_anna/Wave"
output_dir = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Calypte_anna/"
audio_format = "wav"
annot_format = "birdsong-recognition-dataset"
labelset = "1"
train_dur = 10
val_dur = 10
test_dur = 10
annot_file = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/Calypte_anna/Annotation.xml"

[SPECT_PARAMS]
fft_size = 512
step_size = 32
freq_cutoffs = [ 500, 15000,]
thresh = 6.25
transform_type = "log_spect"

[DATALOADER]
window_size = 88

[PREDICT]
batch_size = 10
checkpoint_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Calypte_anna/5Ckpt_400_results_220713_144555/TweetyNet/checkpoints/max-val-acc-checkpoint.pt"
csv_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Calypte_anna/CA_Wave_prep_211110_170103_MASTER.csv"
labelmap_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Calypte_anna/5Ckpt_400_results_220713_144555/labelmap.json"
majority_vote = false
min_segment_dur = 0.05
models = [ "TweetyNet",]
num_workers = 1
output_dir = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Calypte_anna/"
save_net_outputs = false
spect_scaler_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Calypte_anna/5Ckpt_400_results_220713_144555/StandardizeSpect"

[TweetyNet.optimizer]
lr = 0.001
