[PREP]
data_dir = "/users/PYS1065/kprovost/bioacoustics/Sounds_and_Annotations/Calypte_anna/Wave"
output_dir = "/users/PYS1065/kprovost/bioacoustics/Finished_Models/Calypte_anna/"
audio_format = "wav"
annot_format = "koumura"
labelset = "1"
train_dur = 10
val_dur = 10
test_dur = 10
annot_file = "/users/PYS1065/kprovost/bioacoustics/Sounds_and_Annotations/Calypte_anna/Annotation.xml"

[SPECT_PARAMS]
fft_size = 512
step_size = 32
freq_cutoffs = [ 500, 15000,]
thresh = 6.25
transform_type = "log_spect"

[DATALOADER]
window_size = 88

[TRAIN]
models = [ "TweetyNet",]
root_results_dir = "/users/PYS1065/kprovost/bioacoustics/Finished_Models/Calypte_anna/"
batch_size = 10
num_epochs = 10
normalize_spectrograms = true
val_step = 400
ckpt_step = 200
patience = 50
csv_path = "/users/PYS1065/kprovost/bioacoustics/Finished_Models/Calypte_anna/Wave_prep_211110_170103_MASTER.csv"

[TweetyNet.optimizer]
lr = 0.001
