[PREP]
data_dir = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/Zonotrichia.leucophrys/Wave"
output_dir = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/Zonotrichia.leucophrys/"
audio_format = "wav"

[SPECT_PARAMS]
fft_size = 512
step_size = 32
freq_cutoffs = [ 500, 15000,]
thresh = 6.25
transform_type = "log_spect"

[DATALOADER]
window_size = 88

[PREDICT]
batch_size = 10
checkpoint_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Zonotrichia.leucophrys/results_220812_084943/TweetyNet/checkpoints/max-val-acc-checkpoint.pt"
labelmap_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Zonotrichia.leucophrys/results_220812_084943/labelmap.json"
majority_vote = false
min_segment_dur = 0.05
models = "TweetyNet"
num_workers = 1
output_dir = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Zonotrichia.leucophrys/"
save_net_outputs = false
spect_scaler_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Zonotrichia.leucophrys/results_220812_084943/StandardizeSpect"


[TweetyNet.optimizer]
lr = 0.001
