#!/bin/bash

## command to run this file in terminal
## conda activate vak-env; sh /Users/kprovost/Documents/GitHub/bioacoustics/tweetynet/5SPPBALMF/run_tweetynet_5speciesBalancedMF_1train.job

## set flags
TIMESTAMP=`date +%Y-%m-%d_%H-%M-%S` ## get date and time
checkpoint=1 ## run train_checkpoint (vs run train)
runprep=0 ## run the prep step yes/no
runtrain=1 ## run the train step yes/no
folder="/Users/kprovost/Documents/Postdoc_Working/Finished_Models/5SpeciesBalancedMF/"

## one folder for all of the subsetted wav files as well as the Annotation.xml file 

if [ "$checkpoint" == "0" ]; then
	logfile="/Users/kprovost/Documents/Postdoc_Working/Finished_Models/5SpeciesBalancedMF/5SPPBALMF_trainlog_$TIMESTAMP.txt"
else
	logfile="/Users/kprovost/Documents/Postdoc_Working/Finished_Models/5SpeciesBalancedMF/5SPPBALMF_trainlog_checkpoint_$TIMESTAMP.txt"
fi
echo $logfile

## change this folder as needed
cd $folder

export OMP_NUM_THREADS=1
#conda activate vak-env

## before running the "prep" steps from scratch, remember to remove the 5SPPv_path entries

if [ "$checkpoint" == "1" ]; then
	echo "TRANSFER, SKIP PREP STEP" >> $logfile 2>&1
	if [ "$runtrain" == "1" ]; then
		echo "START TRAIN_CHECKPOINT" >> $logfile 2>&1
		date >> $logfile 2>&1
		vak train_checkpoint /Users/kprovost/Documents/GitHub/bioacoustics/tweetynet/5SPPBALMF/5SpeciesBalancedMF_train_checkpoint_50.toml >> $logfile 2>&1 
		echo "FINISHED TRAIN" >> $logfile 2>&1
		date >> $logfile 2>&1
	else
		echo "SKIP TRAIN" >> $logfile 2>&1
		date >> $logfile 2>&1
	fi
fi

echo "DONE" >> $logfile 2>&1
date >> $logfile 2>&1











