[PREP]
data_dir = "~/bioacoustics/Sounds_and_Annotations/Empidonax_virescens/Wave"
output_dir = "~/bioacoustics/Finished_Models/Empidonax_virescens/"
audio_format = "wav"
annot_format = "koumura"
labelset = "1"
train_dur = 10
val_dur = 10
test_dur = 10
annot_file = "~/bioacoustics/Sounds_and_Annotations/Empidonax_virescens/Annotation.xml"

[SPECT_PARAMS]
fft_size = 512
step_size = 32
freq_cutoffs = [ 500, 10000,]
thresh = 6.25
transform_type = "log_spect"

[DATALOADER]
window_size = 88

[TRAIN]
models = [ "TweetyNet",]
root_results_dir = "~/bioacoustics/Finished_Models/Empidonax_virescens/"
batch_size = 3
num_epochs = 10
normalize_spectrograms = true
val_step = 50
ckpt_step = 200
patience = 5
csv_path = "~/bioacoustics/Empidonax_virescens/Wave_prep_211110_160409_MASTER.csv"

[TweetyNet.optimizer]
lr = 0.001

