[PREP]
data_dir = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/9SppBalanced/"
output_dir = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/9SppBalanced/"
audio_format = "wav"
annot_format = "birdsong-recognition-dataset"
labelset = "1"
train_dur = 10
val_dur = 10
test_dur = 10
annot_file = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/9SppBalanced//Annotation.xml"

[SPECT_PARAMS]
fft_size = 512
step_size = 32
freq_cutoffs = [ 500, 15000,]
thresh = 6.25
transform_type = "log_spect"

[DATALOADER]
window_size = 88

[TRAIN]
batch_size = 10
ckpt_step = 200
models = [ "TweetyNet",]
normalize_spectrograms = true
num_epochs = 10
patience = 400
root_results_dir = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/9SppBalanced/"
val_step = 400
csv_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/9SppBalanced/9SppBalanced_prep_220822_133718_MASTER.csv"

[TweetyNet.optimizer]
lr = 0.001
