[PREP]
data_dir = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/Calypte.anna/Wave"
output_dir = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Calypte.anna/"
audio_format = "wav"
annot_format = "birdsong-recognition-dataset"
labelset = "1"
train_dur = 10
val_dur = 10
test_dur = 10
annot_file = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/Calypte.anna/Annotation.xml"

[SPECT_PARAMS]
fft_size = 512
step_size = 32
freq_cutoffs = [ 500, 15000,]
thresh = 6.25
transform_type = "log_spect"

[DATALOADER]
window_size = 88

[LEARNCURVE]
batch_size = 10
ckpt_step = 200
csv_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Calypte.anna/Wave_prep_220715_112238.csv"
models = [ "TweetyNet",]
normalize_spectrograms = true
num_epochs = 10
num_replicates = 10
num_workers = 1
patience = 5
previous_run_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Calypte.anna/results_220715_134012/"
root_results_dir = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Calypte.anna/"
train_set_durs = [ 30, 45, ]
val_step = 400

[TweetyNet.optimizer]
lr = 0.001
