[PREP]
data_dir = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/Passerina.amoena/Wave"
output_dir = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/Passerina.amoena/"
audio_format = "wav"
annot_format = "birdsong-recognition-dataset"
labelset = "1"
train_dur = 10
val_dur = 10
test_dur = 10
annot_file = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/Passerina.amoena/Annotation.xml"

[SPECT_PARAMS]
fft_size = 512
step_size = 32
freq_cutoffs = [ 500, 15000,]
thresh = 6.25
transform_type = "log_spect"

[DATALOADER]
window_size = 88

[EVAL]
batch_size = 10
csv_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Passerina.amoena/PA_Wave_prep_220811_133846_MASTER.csv"
device = "cpu"
models = [ "TweetyNet",]
output_dir = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Passerina.amoena/"
spect_scaler_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Calypte.anna/results_220817_151217/StandardizeSpect"
labelmap_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Calypte.anna/results_220817_151217/labelmap.json"
checkpoint_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Calypte.anna/results_220817_151217/TweetyNet/checkpoints/max-val-acc-checkpoint.pt"


[TweetyNet.optimizer]
lr = 0.001
