[PREP]
data_dir = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/Calypte.anna/Wave"
output_dir = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Calypte.anna/"
audio_format = "wav"
annot_format = "birdsong-recognition-dataset"
labelset = "1"
train_dur = 10
val_dur = 10
test_dur = 10
annot_file = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/Calypte.anna/Annotation.xml"

[SPECT_PARAMS]
fft_size = 512
freq_cutoffs = [ 500, 15000,]
step_size = 32
thresh = 6.25
transform_type = "log_spect"

[DATALOADER]
window_size = 88

[EVAL]
batch_size = 10
checkpoint_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Myiarchus.tuberculifer/results_220803_124629/TweetyNet/checkpoints/max-val-acc-checkpoint.pt"
csv_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Calypte.anna/CA_Wave_prep_211110_170103_MASTER.csv"
device = "cpu"
labelmap_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Myiarchus.tuberculifer/results_220803_124629/labelmap.json"
models = [ "TweetyNet",]
num_workers = 1
output_dir = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Calypte.anna/"
spect_scaler_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Myiarchus.tuberculifer/results_220803_124629/StandardizeSpect"

[TweetyNet.optimizer]
lr = 0.001
