[PREP]
data_dir = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/Calypte_anna/Wave"
output_dir = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Calypte_anna/"
audio_format = "wav"
annot_format = "koumura"
labelset = "1"
train_dur = 10
val_dur = 10
test_dur = 10
annot_file = "/Users/kprovost/Documents/Postdoc_Working/Sounds_and_Annotations/Calypte_anna/Annotation.xml"

[SPECT_PARAMS]
fft_size = 512
step_size = 32
freq_cutoffs = [ 500, 10000,]
thresh = 6.25
transform_type = "log_spect"

[DATALOADER]
window_size = 88

[TRAIN_CHECKPOINT]
checkpoint_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Calypte_anna/CA_Patience5_Model_results_211115_171320/max-val-acc-checkpoint.pt"
labelmap_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Calypte_anna/CA_Patience5_Model_results_211115_171320/labelmap.json"
spect_scaler_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Calypte_anna/CA_Patience5_Model_results_211115_171320/StandardizeSpect"
batch_size = 3
ckpt_step = 200
models = [ "TweetyNet",]
normalize_spectrograms = true
num_epochs = 10
patience = 45
val_step = 50
csv_path = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Calypte_anna/CA_Wave_prep_211110_170103_MASTER.csv"
root_results_dir = "/Users/kprovost/Documents/Postdoc_Working/Finished_Models/Calypte_anna/"

[TweetyNet.optimizer]
lr = 0.001
